# This pipeline will run prettier on all files in the repository

name: Code Quality checks

on:
  - push
  - pull_request

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run prettier:check
